select * from customer
-- What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer where discount_applied='Yes' and 
purchase_amount>=(select avg(purchase_amount) from customer)
-- Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2)
as Average_review from customer group by item_purchased 
order by Average_review desc limit 5

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) from customer 
where shipping_type in ('Standard','Express') group by shipping_type
-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue,
(case when subscription_status='Yes' then 'Subscribed' else 'Not Subscribed' end) as Subscripted
from customer group by subscription_status
ORDER BY total_revenue desc,average_spend desc
-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
-- What are the top 3 most purchased products within each category?
with item_count as
(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc)as item_rank from customer
group by category,item_purchased
)
select category,item_purchased,total_orders,item_rank from item_count where item_rank <=3
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;